# Nightly-only features
unstable_features = true

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# Function formatting
fn_single_line = true
format_macro_bodies = true

# Struct formatting
struct_field_align_threshold = 20

# Other
edition = "2024"
